site_name: Continuous Delivery Engine
site_description: Building Continuous Delivery Pattern using Developer Hub, Serverless Workflows, OpenShift and EDA.
site_author: Nikhil Sharma
repo_url: https://github.com/niksharma20/Continuous-Delivery-Engine
repo_name: niksharma20/Continuous-Delivery-Engine

extra:
  collaborator: Ismail Dhaoui
  collaborator_url: https://github.com/idhaoui
  site_usecase: "Use Case: Namespace Goverance"

theme:
  name: material
  custom_dir: theme
  palette:
    - primary: red
      accent: red
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest

nav:
  - Home: index.md
