site_name: CDE
site_description: Building Continuous Delivery Pattern using Developer Hub, Serverless Workflows, OpenShift and EDA.
site_author: Nikhil Sharma
repo_url: https://github.com/niksharma20/Continuous-Delivery-Engine
repo_name: niksharma20/Continuous-Delivery-Engine

extra:
  collaborator: Ismail Dhaoui
  collaborator_url: https://github.com/idhaoui

theme:
  name: material
  palette:
    primary: red
    accent: red
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest

nav:
  - Home: index.md
  - Setup: docs/content/setup/setup.md
  - Module 1: docs/content/modules/module_1/module1.md
  - Module 2: docs/content/modules/module_2/module2.md
  - Module 3: docs/content/modules/module_3/module3.md
  - Conclusion: docs/content/conclusion/conclusion.md
