site_name: Red Hat Tech Day Netherlands - Continuous Delivery Engine
site_description: Building Continuous Delivery Pattern using Developer Hub, Serverless Workflows, Event Driven Ansible and Openshift.
site_author: Nikhil Sharma
site_url: https://github.com/niksharma20/Continuous-Delivery-Engine
repo_url: https://github.com/niksharma20/Continuous-Delivery-Engine
repo_name: niksharma20/Continuous-Delivery-Engine

extra:
  collaborator: Ismail Dhaoui
  collaborator_url: https://github.com/idhaoui

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js

theme:
  name: material
  palette:
    primary: red
    accent: red
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    
plugins:
  - search
  - include-markdown
  
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md
  - Setup: content/setup/setup.md
  - Declarative Infrastructure: content/modules/module_1/module1.md
  - EDA for Openshift: content/modules/module_2/module2.md
  - Enforcing Governance via IDP: content/modules/module_3/module3.md
  - Conclusion: content/conclusion/conclusion.md
